Updated README
openedx-unsupported/devstack pull request #113
Opened 2017-05-10 12:26 UTC by clintonb

2017-05-10 12:27 UTC, clintonb commented
FYI @edx/docker-devstack-working-group

2017-05-10 16:29 UTC, gsong approved these changes

2017-05-10 17:33 UTC, jbarciauskas requested changes

2017-05-10 17:33 UTC, jbarciauskas commented on README.md
> +memory, configure Docker with 4 cores (CPUs) and 8 GB of memory.
I'd prefer to stick with the minimum requirements rather than say "half" -- particularly 4GB of RAM we know is a hard minimum.

2017-05-10 17:35 UTC, clintonb commented on README.md
> +memory, configure Docker with 4 cores (CPUs) and 8 GB of memory.
Developers will be at a disadvantage with 2 CPUs and 4 GB of memory. I haven't used that configuration almost since I wrote the README because it's not very usable.

2017-05-10 17:48 UTC, jbarciauskas commented on README.md
> +memory, configure Docker with 4 cores (CPUs) and 8 GB of memory.
OK, it's seemed mostly fine on my Macbook. We should just rephrase as minimum and highly suggested then?

2017-05-11 18:45 UTC, nedbat commented
I made #115 to match these changes in README.rst

2017-05-11 20:49 UTC, clintonb commented
See #113

2017-05-11 20:49 UTC, closed without merging