Moving Pycharm notes to the RST file
openedx-unsupported/devstack pull request #128
Opened 2017-05-31 12:16 UTC by staubina

PR to move @robrap and @clintonb Pycharm notes to the RST file and also update some of the docs with my experience thus far.

2017-05-31 13:32 UTC, staubina commented
Originated in this PR, https://github.com/edx/devstack/pull/73

2017-05-31 13:40 UTC, staubina commented on README.rst
> +
Note: Github is styling this section oddly, it looks correct in other RST preview tools.  I can change it if there are concerns about it.

2017-05-31 16:55 UTC, robrap requested changes
In addition the documents changes, I'd personally do the following:
1. Add a docs directory.
2. Make a pycharm.rst in the docs directory.
3. Move these changes to the new file, and just add a small section with pointer from the README.rst.

Not sure if others would agree, so maybe ask @clintonb  or others before doing this refactor.

2017-05-31 16:55 UTC, robrap commented on README.rst
> +A number of edX engineers develop using `PyCharm`_. As of version 2017.1,
Maybe simplify as follows:

The Professional edition of JetBrains PyCharm IDE, version 2017.1 or later, can be used to develop and debug with Docker and Docker Compose.

2017-05-31 16:55 UTC, robrap commented on README.rst
> +    -  /LOCAL/PATH/TO/devstack/docker-compose.yml (e.g.~/edx/devstack/docker-compose.yml)
Can these all use `$DEVSTACK_WORKSPACE` and drop the examples?

2017-05-31 16:55 UTC, robrap commented on README.rst
> +  -  DEVSTACK\_WORKSPACE=/LOCAL/PARENT/PATH/TO(/devstack) (e.g. ~/edx)
Maybe drop the `(e.g. ~/edx)` and use the following:

DEVSTACK_WORKSPACE=`</LOCAL/PARENT/PATH/OF/DEVSTACK/REPO/CLONE>`

2017-05-31 16:55 UTC, robrap commented on README.rst
> +
It would be nice if we could fix this, but I don't know what it is doing wrong.  I tried messing with it for a bit.

2017-05-31 16:55 UTC, robrap commented on README.rst
> +    -  /edx/app//venvs//bin/python
Should be something like:
```
/edx/app/<SERVICE_NAME>/venvs/<SERVICE_NAME>/bin/python
```

2017-05-31 16:55 UTC, robrap commented on README.rst
> +  - On a Mac, you'll need to use "API URL: unix:///var/run/docker.sock" (with 3 slashes).
I would add the double \`\` around paths and parts that should be copied.

2017-05-31 16:55 UTC, robrap commented on README.rst
> +**Note** If you are running with Docker Sync you will also need to first
1. Relabel as Important.
2. Move this as the first note.
3. Possibly add this to the Troubleshooting section.  For example, "If you see your breakpoints and code out of sync..."

2017-05-31 16:55 UTC, robrap commented on README.rst
> +modified ``manage.py``. (We should fix this!!!)
I'd drop the `(We should fix this!!!)`.

2017-05-31 16:55 UTC, robrap commented on README.rst
> +TODO: Fix Cython for debug
Move to a sub-bullet under "PyCharm Debugging" in the checklist below.  Other sub-bullets could include "Bokchoy Debugging".  "Debugging unit tests with templates".  Maybe also add "Debugging Servers" and "Debugging Unit Tests" that are checked, so it is clear that this is partly complete?

2017-05-31 16:55 UTC, robrap commented on README.rst
> +Configuration <https://www.jetbrains.com/help/pycharm/2017.1/run-debug-configuration-django-server.html>`__.
Should this reference move to the bottom?

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +    -  /edx/app//venvs//bin/python
Too many slashes.

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +set of configuration (compose) files, I recommend you create a new one
s/I/we

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +service dropdown gets reset. Remember to restore to the IDA you wish to
Premature newline.

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +modified ``manage.py``. (We should fix this!!!)
Remove the parenthetical.

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +Remaining Work
This section should go away.

2017-05-31 17:08 UTC, clintonb commented on README.rst
> +TODO: Fix Cython for debug
This should go away and/or be added to a known issues section.

2017-05-31 17:08 UTC, clintonb commented
If we are going to restructure, we should move everything to a docs directory.

2017-05-31 18:37 UTC, staubina commented
@clintonb I was simply copying over the existing changes that are sitting on the other PR.  I agree that a Docs directory might be useful soon as this file contains a lot of great contextual information.

@robrap @clintonb I will work on the suggested changes as soon as I can.

2017-06-05 21:32 UTC, robrap commented on README.rst
> +Remaining Work
@clintonb @staubina: I think we agreed that the README should contain details of "Features not (yet) supported".  Even if not formatted as a to do list, I think this new doc should mention what is not yet supported (or under development) in regards to PyCharm integration.

As part of a separate PR, this should include things like Forums.

2017-06-05 21:34 UTC, robrap commented
@staubina Let me know how I can help you with this.  I think we should treat the docs more like the wiki, and allow imperfect changes to merge with small PRs to improve, rather than waiting forever before anything makes it to master.

Given that, I would like to see this in its own doc to not make the README way too long.  Let me know if I can help with the refactor without stepping on your toes @staubina. Thanks.

2017-06-05 21:42 UTC, macdiesel commented
I am a +1 using these docs more like a wiki.

2017-06-06 11:49 UTC, staubina commented
@robrap I agree 100%.  This PR has been open in 2 forms for way to long.

People are starting to use Pycharm and missing out on these docs. I will try to close this right after I clean up my story PR.

2017-06-06 12:50 UTC, staubina commented on README.rst
> +    -  /LOCAL/PATH/TO/devstack/docker-compose.yml (e.g.~/edx/devstack/docker-compose.yml)
Lets test this and then add it in a later PR

2017-06-06 12:50 UTC, staubina commented on README.rst
> +  -  DEVSTACK\_WORKSPACE=/LOCAL/PARENT/PATH/TO(/devstack) (e.g. ~/edx)
Same as above lets try this and add it later.

2017-06-06 13:06 UTC, staubina commented
@robrap @clintonb @macdiesel Updates pushed.  Please review again when you have a moment.  I will probably only wait for 1 thumb on this one.

2017-06-06 18:57 UTC, robrap approved these changes
@staubina If you like my minor clean-up, you are all good to squash then merge.  Thank you!  👍

2017-06-07 11:51 UTC, merged