Add Makefile command to print logs of specific container.
openedx-unsupported/devstack pull request #137
Opened 2017-06-06 08:50 UTC by vkaracic

Instead of listing all the logs, or having to append the grep command each time, this command will allow outputting the logs of a specific container only. Particularly useful if you want to read the traceback of an error that has been intertwined with lines of logs from other services.

Thoughts @edx/docker-devstack-working-group ?

2017-06-06 15:37 UTC, robrap requested changes
@edx/docker-devstack-working-group We still need to have a general conversation about what is important enough to add to the make file, and what becomes a separate doc of tips and tricks.  Are we ok with just adding more and more to make?

2017-06-06 15:37 UTC, robrap commented on Makefile
> +%-logs: ## View the logs of the specified service container
Either needs a TODO like `%-shell:` and/or some resolution on help text.

2017-06-06 15:37 UTC, robrap commented on README.rst
> +    make <target>-logs
Maybe use similar pattern to `shell`:
```
To view the logs of a specific service container, run ``make <service>-logs``.
For example to access the logs for Catalog/Course Discovery Service, you can run:
 
 .. code:: sh
 
     make discovery-logs
```
Note calling it "service" instead of "target" for consistency.

2017-06-06 15:57 UTC, vkaracic commented
Very well. I would argue that if you do decide to keep a command for the logs that you decide on this, or something like this one, I find it to be much more useful instead of scrolling through the logs of all services to find what you look for.

2017-06-06 16:14 UTC, vkaracic commented on Makefile
> +%-logs: ## View the logs of the specified service container
Does the TODO on the `%-shell` mean that the help for it should print something like:
```
...
lms-shell (...)
studio-shell (...)
ecommerce-shell (...)
...
```
?

2017-06-06 17:28 UTC, robrap commented
@vkaracic I agree that this one seems close enough to the existing `logs` target.  That wasn't meant to be a blocker on this ticket.  I was just trying to kick off that conversation.

Just the minor clean-up before I'd give thumbs.

2017-06-06 17:31 UTC, robrap commented on Makefile
> +%-logs: ## View the logs of the specified service container
I'm not sure.  I don't know if we should enumerate services for each of these, or have something like the following that gives a single example:
```
SERVICE-shell Run a shell on the service container (e.g. "make lms-shell" for LMS).
```

2017-06-07 12:29 UTC, vkaracic commented
@robrap comments addressed. After this PR I could work on the TODO's in the Makefile. I have a couple of ideas for more commands as well.
How many reviews would this PR need in order to merge it?

2017-06-07 12:40 UTC, robrap approved these changes
We'll ask in HipChat, but I think we should be using 1 thumb on simple PRs. 👍

2017-06-07 12:45 UTC, robrap commented
@vkaracic I say you merge when it is green.

2017-06-07 13:01 UTC, clintonb approved these changes

2017-06-07 13:01 UTC, clintonb commented on Makefile
> +# TODO: Print out help for this target.
Remove the TODO.

2017-06-07 13:11 UTC, robrap commented
@clintonb I had @vkaracic add the TODO for consistency. ;)  Either way, sounds like @vkaracic is looking to solve the help issue in a follow-up PR, so that's better than a TODO. :)

2017-06-07 13:35 UTC, merged

2017-06-16 22:22 UTC, clintonb commented on Makefile
> +	docker-compose logs -f | grep edx.devstack.$*
You don't need `grep`. See https://docs.docker.com/compose/reference/logs/.

You can simply call `docker-compose logs -f $*`.