Watch edx-platform assets
openedx-unsupported/devstack pull request #210
Opened 2017-08-15 19:26 UTC by efischer19

# [PLAT-1663](https://openedx.atlassian.net/browse/PLAT-1663)

Essentially, I'm modifying the launch command for both `lms` and `studio` to kick off a `paver watch_assets` background process.

Work in progress, pairs with edx-platform PR to be linked shortly once I've made it. This seemingly works on my local setup.

FYI @arizzitano @macdiesel

2017-08-15 19:30 UTC, clintonb requested changes
Docker containers are supposed to run one process. If you need to run another process, spin up another container. It would be ideal if that container was based on an image that is specially-purposed for asset compilation.

2017-08-15 19:30 UTC, clintonb commented
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#each-container-should-have-only-one-concern

2017-08-15 19:31 UTC, clintonb commented
@gsong and I discussed some ideas about this a couple hours ago at lunch. Let me know if you'd like to chat further.

2017-08-16 18:13 UTC, macdiesel commented
@clintonb this may be a bit of an overstatement, I have found this in the docker documentation:
https://docs.docker.com/engine/admin/multi-service_container/

"It is generally recommended that you separate areas of concern by using one service per container. That service may fork into multiple processes (for example, Apache web server starts multiple worker processes). **It’s ok to have multiple processes**, but to get the most benefit out of Docker, avoid one container being responsible for multiple aspects of your overall application."

To be honest, I'm not sure that this is something that would benefit from being in multiple containers as it's tied directly to django serving of assets while in development mode. 

Perhaps what would be better here would be to start using the supervisor process to launch both the Django app as well as the asset watcher.

2017-08-18 14:57 UTC, efischer19 commented
This (how/if to handle multi-process containers) seems like it's going to be a fairly in-depth discussion, I've created a wiki page here: https://openedx.atlassian.net/wiki/spaces/~efischer/pages/163090911/Docker+multi-process+ruminations

2017-09-21 16:51 UTC, gsong commented
Addressed with #230.

2017-09-21 16:51 UTC, closed without merging