Add docker-compose restart commands to Makefile
openedx-unsupported/devstack pull request #215
Opened 2017-08-22 16:51 UTC by UmanShahzad

I was getting tired of typing `docker-compose restart <service>` which is slightly longer than `make lms-restart` or just `make restart` for everything, so added these here.

Along with it, updated some relevant parts of the documentation (and very minor spacing issues that were causing bad rendering).

2017-08-22 16:56 UTC, clintonb requested changes
I like the documentation changes, but would prefer we not try to create a Make target for every Docker command. Just use Docker! 

Also, why do you need to consistently restart containers?

2017-08-22 17:14 UTC, UmanShahzad commented
@clintonb Haha, right, I didn't like the solution too much either in general, it was just for my convenience. But in that case, it'd be more reasonable to git-ignore some file type which we can then include in the main Makefile, allowing people their own commands without having unstaged work sitting around. Since we already include `*.mk`, let's just move those into `Makefile` and gitignore it for the future?

Also, I was messing around a little with the containers which lead me to have to restart them, but not anymore. Still, since the above possibility came up, maybe we can do something about it.

2017-08-23 08:37 UTC, UmanShahzad commented
@clintonb I pushed a solution that implements my above comment's suggestion.

Now I put the restart commands into my `convenience.mk`, and will probably be adding much more convenience commands :)

2017-08-23 11:16 UTC, clintonb requested changes
Start small. Revert all of these changes, because you've now gone in a worse direction by combining marketing targets in this manner. Just ignore one file, local.mk, and document how users can add their own targets.

2017-08-23 11:16 UTC, clintonb commented on Makefile
> +
Revert these changes. There is already a separate file for the marketing site. Marketing site targets should always be there as it is not part of Open EdX.

2017-08-23 11:16 UTC, clintonb commented on README.rst
> -simply use the ``docker-compose restart`` command:
Revert your changes about restarts.

2017-08-23 11:16 UTC, clintonb commented on README.rst
> +Available Services
This should be close to the top of the document, not the bottom.

2017-09-08 07:05 UTC, UmanShahzad commented
@clintonb I will be getting to this now -- sorry for the delay!

2017-09-08 07:20 UTC, UmanShahzad commented
@clintonb Thanks for the review. I undid the Makefile changes, allowing instead for a single `local.mk` for convenience make targets. Also updated the documentation to move the service list up to a better context, and add a note about the existence of `local.mk`.

2017-09-08 12:36 UTC, clintonb commented on README.rst
> +.. _available services:
I'm on the fence about this section. The table below informs the user which services are installed. I'm not certain what additional value this new section adds. I'm also concerned it will grow stale, as the table below his since it lacks a URL for the forums service.

What value do you gain from this list that is not gained from the table or opening the docker-compose file? How did you determine which services are available?

2017-09-08 20:36 UTC, UmanShahzad commented on README.rst
> +.. _available services:
I'd prefer to just scratch it, it doesn't really matter.

2017-09-08 20:37 UTC, UmanShahzad commented
@clintonb In order to keep the diff clean and let https://github.com/edx/devstack/pull/224 take care of the doc nits, I'll be just totally undoing the `README` changes minus the note about `local.mk`, and this PR will just be about allowing convenience commands through that `local.mk`.

2017-09-08 22:53 UTC, clintonb approved these changes

2017-09-21 16:56 UTC, merged