TE-2639 Support for named release images
openedx-unsupported/devstack pull request #325
Opened 2018-07-09 19:47 UTC by jmbowman

Use [docker-compose variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) to more easily support using devstack Docker images for named Open edX releases.

We'll want to hold off on merging this until ``edx-e2e-tests`` has been tagged for release and we have a full set of ``hawthorn.master`` images so we can test it properly.

2018-07-09 20:13 UTC, nedbat requested changes

2018-07-09 20:13 UTC, nedbat commented on README.rst
> +   or ``hawthorn.rc1``.
For devstack, people should probably always be on a ".master" branch.  But for their own development, they will need to be on their own fork, right?  Do we have a way to support that?

2018-07-09 20:13 UTC, nedbat commented on README.rst
> +   "hawthorn.master", "zebrawood.rc1", etc.
"Note that unlike a server install, OPENEDX_RELEASE should not have the 'open-release/' prefix."

2018-07-09 20:13 UTC, nedbat commented on README.rst
> +   should handle this for you once you've set the environment variable above.
Can we say this as "Use `make dev.checkout` to check out the correct branch in the local checkout of each service repository."  ?  Is there ever a reason they'd want to not use dev.checkout?

2018-07-09 20:13 UTC, nedbat commented on README.rst
> +   should handle this for you once you've set the environment variable above.
Also, "once you've set the OPENEDX_RELEASE environment variable above."

2018-07-09 20:13 UTC, nedbat commented on README.rst
> +All ``make`` targes and ``docker-compose`` calls should now use the correct
"targes"

2018-07-09 20:13 UTC, nedbat commented on docker-compose.yml
> +    image: edxops/elasticsearch:${OPENEDX_RELEASE:-latest}
This had been "devstack", but now defaults to "latest"

2018-07-09 20:27 UTC, jmbowman commented on README.rst
> +   or ``hawthorn.rc1``.
Most changes can still use the pre-built images for the branch they were derived from.  If they make more extensive changed to dependencies or such, they can build their own images using the instructions above.

2018-07-09 20:58 UTC, nedbat commented on README.rst
> +   or ``hawthorn.rc1``.
Oh, right.  I keep getting confused between pulling images, and pulling code.

2018-07-12 12:06 UTC, nedbat approved these changes

2018-07-20 20:19 UTC, merged