Added a howto for overriding installed packages
openedx-unsupported/devstack pull request #340
Opened 2018-10-02 12:28 UTC by davestgermain

@nedbat I think this is the simplest way to start developing with an included package, but I don't know if it's the approved way. Regardless, there's a gap in our other repos' documentation, which simply say ``make install`` (neglecting to specify how to install the package within docker).

2018-10-02 17:23 UTC, nedbat requested changes

2018-10-02 17:23 UTC, nedbat commented on README.rst
> +run ``python setup.py develop``, and restart the service.
Why not `pip install -e /edx/src/your-package` ?

2018-10-02 17:23 UTC, nedbat commented on README.rst
> +How do I develop on an installed python package?
"Python" please :)

2018-10-02 18:01 UTC, davestgermain commented
@nedbat thanks, I corrected it.

2018-10-04 20:30 UTC, nedbat approved these changes

2018-10-04 20:43 UTC, merged