Update gradebook container to have Node:12 version
openedx-unsupported/devstack pull request #459
Opened 2019-12-06 15:57 UTC by schenedx

Update the gradebook container node version from 10 to 12

@edx/masters-devs Please review.

2019-12-06 16:04 UTC, iloveagent57 approved these changes
LGTM (assuming tests pass)

2019-12-09 14:30 UTC, abutterworth commented
Looks like the PR travis build took 50 mins to run and was canceled due to exceeding a build time limit. Is this normal for devstack? (I just restarted the travis build)

2019-12-09 16:00 UTC, kdmccormick commented
@abutterworth Unfortunately, it is normal for devstack. I don't know of a workaround; I ended just merging my last devstack PR with tests failing.

@jmbowman mentioned that the fix would likely be making provisioning faster.

2019-12-09 16:01 UTC, kdmccormick commented
Looks like @jinder1s is/was working on the issue: https://github.com/edx/devstack/pull/458

2019-12-09 16:20 UTC, matthugs approved these changes

2019-12-09 16:21 UTC, matthugs requested changes
Oh wait actually I almost forgot

2019-12-09 16:21 UTC, matthugs commented on docker-compose.yml
>        file: microfrontend.yml
We should change this upstream in this file, which is shared between this and the programs learner portal iirc.

2019-12-09 16:26 UTC, schenedx commented on docker-compose.yml
>        file: microfrontend.yml
@matthugs What should we change here? The content in `microfrontend.yml` has node at v10. That's not going out of support by end of year. @abutterworth because we can leave that in for now.

2019-12-09 16:28 UTC, kdmccormick commented on docker-compose.yml
>        file: microfrontend.yml
I support updating it in `microfrontend.yml`, because only Gradebook and ProgramManager use that file.

2019-12-09 16:53 UTC, schenedx commented on docker-compose.yml
>        file: microfrontend.yml
OK, I upgraded the node version on `microfrontend.yml`. This also means we can remove the `image` override we have in `docker-compose.yml`. @matthugs and @kdmccormick Please review again

2019-12-09 18:04 UTC, matthugs approved these changes

2019-12-09 19:03 UTC, merged