Make no_cache option consistent
openedx-unsupported/devstack pull request #485
Opened 2020-03-04 21:22 UTC by jdmulloy

2020-03-05 21:00 UTC, jmbowman approved these changes
Looks good other than that one question.

2020-03-05 21:00 UTC, jmbowman commented on Makefile
> +	echo "no_cache set: Not running %./programs/provision.sh cache"
Why the "%" only in this version of the echo statement?

2020-03-05 21:00 UTC, kdmccormick approved these changes
Great change, thanks!

2020-03-05 22:09 UTC, jdmulloy commented on Makefile
> +	echo "no_cache set: Not running %./programs/provision.sh cache"
I think it's a typo. I'll remove it.

2020-03-06 09:55 UTC, awaisdar001 commented on Makefile
> +ifdef no_cache
what about making it a little readable?

```
ifdef cache_programs
	$(WINPTY) bash ./programs/provision.sh cache
else
	echo "cache_programs set: Not running bash ./programs/provision.sh cache"
endif
```

Now if we run `make dev.up.lms` I won't run the caching. `make cache_programs=True dev.up.lms` will do the caching. 

Is the expected behavior is to run caching by default? I am not sure at this moment. 
Just a nit, but let me know what you think.
Thanks.

2020-03-06 12:45 UTC, kdmccormick commented on Makefile
> +ifdef no_cache
A lot of devs depend on programs being cached by default, such as those of us working on Master's programs. On the other hand, a lot of devs probably don't need programs, and the by-default caching is slowing them down. I don't know right now who is in the majority.

I do like the suggestion of making it a positive flag (`cache_programs=True/False`) instead of a negative one.

My feeling is that we should leave `cache_programs=True` as default for this PR to avoid breaking anyone's flow. Then, if we want to, propose making `False` the default in another PR, but also tag some of the people who will be impacted for review.

2020-03-06 12:47 UTC, kdmccormick commented on Makefile
> +ifdef no_cache
A nice middle ground would beg providing an easy way for devs to toggle caching On or Off without having to include it in each command. For example, having a git-ignored `.env.local` file that gets loaded when running each `make` target

2020-03-10 13:38 UTC, regisb commented
I just realised this PR exists. As suggested in #491 (which I just opened) I strongly suggest *not* caching programs by default. This command makes zero sense for 90% of Open edX developers. Instead of relying on `no_cache=True`, I think it would be better if developers explicitely ran `make dev.up dev.provision.programs` instead of `make dev.up`.

2020-03-11 13:07 UTC, kdmccormick requested changes
I recommend closing this, as it's been achieved as part of https://github.com/edx/devstack/pull/491

2020-04-01 20:09 UTC, closed without merging