Simplify some CI and health-checking logic
openedx-unsupported/devstack pull request #505
Opened 2020-03-27 14:42 UTC by kdmccormick

2020-04-06 17:01 UTC, alanoe commented on Makefile
> +dev.onlypull.%: ## Pull latest Docker images for services (separated by plus-signs).
IMHO dev.onlypull is not a good target name, as it is not obvious what it means. I'd recommend to pick a name which describes better what it will be done, eg dev.pull-without-deps

2020-04-06 17:06 UTC, alanoe commented on Makefile
> +backup: dev.up.mysql+mongo+elasticsearch ## Write all data volumes to the host.
If I understood it right, a devstack must have been created with "make dev.provision" before using this. it'd be nice to mention it somewhere

2020-04-06 17:14 UTC, alanoe commented on Makefile
> +%-restart: ## Kill a service's Django development server. The watcher process should restart it.
- it'd be better to create a new restart_django_web_server shell script for restarting Docker containers which run a Django development web server. Its input parameter would be docker_name and python_web_server_command and it could be reused for restarting CMS and LMS.

- Do all components which do not have an explicit <component>-restart make target (eg all except LMS and CMS) can be restarted with this command? One that comes to my mind is cs_comments_service, which is not a Django app, but rather a Sinatra (Ruby) app. With this new command, "make forum-restart" will print an error saying that "manage.py" was not found, which will confuse the user.

2020-04-06 17:18 UTC, alanoe commented on check.sh
> +set -o pipefail
add "set -u", which checks undefined variables

2020-04-06 17:21 UTC, alanoe reviewed
Could you move the file renaming to a separate patch so that we could see the cleanup diff and explain the reason of the file renaming?

2020-04-06 17:25 UTC, alanoe commented on Makefile
> +SUPPORTING_COMPOSE_FILES=-f docker-compose-host.yml -f docker-compose-themes.yml
minor: this var name does not make clear that is used for volume mounting. I recommend using COMPOSE_FILES_FOR_VOLUME_MOUNTS and removing SUPPORTING from the names of the vars below too.

2020-04-06 17:27 UTC, alanoe commented on Makefile
> +ALL_SERVICE_COMPOSE_FILES=\
minor: SERVICES_COMPOSES_FILES is shorter and conveys the same meaning

2020-04-06 17:31 UTC, alanoe commented on Makefile
> +FULL_COMPOSE_SUITE=$(ALL_SERVICE_COMPOSE_FILES) $(SUPPORTING_COMPOSE_FILES)
minor: this name is a little confusing, as a suite with NFS would be full too. I recommend FULL_COMPOSE_SUITE_WITH_VOLUME_MOUNT instead to make it clearer it uses local mounts instead of NFS.

2020-04-06 17:35 UTC, alanoe commented on Makefile
> +ANALYTICS_COMPOSE_SUITE=$(STANDARD_COMPOSE_SUITE) $(ANALYTICS_COMPOSE_FILE)
minor: I'd make it clearer that the first suite uses local mounts. Suggestions: STD_COMPOSE_SUITE_WITH_LOCAL_MOUNTS, STD_COMPOSE_SUITE_WITH_NFS, STD_COMPOSE_SUITE_WITH_DOCKER_SYNC

2020-04-06 17:36 UTC, alanoe commented on Makefile
> +SUPPORTING_COMPOSE_FILES_FOR_SYNC=-f docker-compose-sync.yml
minor: I'd make it clearer that you're referring to docker-sync here (ie. SYNC => DOCKER_SYNC)

2020-04-06 17:38 UTC, alanoe reviewed
clarfiy => clarify in commit msg

2020-04-08 13:40 UTC, kdmccormick commented
Thanks for the review @alanoe . I'm swamped with other work this week, but I'll hopefully be able to address your comments soon.

2020-04-13 16:15 UTC, kdmccormick commented on Makefile
> +backup: dev.up.mysql+mongo+elasticsearch ## Write all data volumes to the host.
Not necessarily. This will just bring up the databases and dump them to a tar file, whether or not there's any provisioned data.

2020-04-13 19:21 UTC, kdmccormick commented on Makefile
> +%-restart: ## Kill a service's Django development server. The watcher process should restart it.
I agree that a solution that works across all containers would be nice. There is already a `devstack.sh` file in every container, with `start`, `exec`, and `open` (i.e. `shell`) commands -- `restart` could be added. Unfortunately, that's out of the scope of my work here.

The Makefile target as-is does not generalize to all the web services in Devstack. It only works for the services that are Python/Django and don't do the strange two-apps-in-one thing that edx-platform does.

I see two approaches I could take:

* Make it clear that this is Python/Django specific by naming the target `%-restart-django`. Then, alias existing restart commands to `$xyz-restart-django` for backwards compatibility.

* Keep the target name generic (`%-restart`). For all services that do not support the standard implementation, either write a custom implementation like you are doing in #512 with `forum-restart`, or implement the target with `docker-compose restart $service`

Do either of those sound good?

2020-04-14 16:06 UTC, kdmccormick commented on Makefile
> +SUPPORTING_COMPOSE_FILES=-f docker-compose-host.yml -f docker-compose-themes.yml
As I thought about the comments you left regarding the names of the Docker Compile file Makefile variables, I realized that the whole set-up I was going for with the names was overly complicated.

I've pushed a new commit "Simplify Makefile handling of docker-compose files" that takes a new approach. It defines two new options--`SYNC_STRATEGY` and `DEFAULT_SERVICES`--which define which file synchronization strategy (local-mount/nfs/docker-sync) and service set are used by generic commands like `make dev.up` and `make dev.provision`. With those options in place, we can conditionally set a value for `DOCKER_COMPOSE_FILES` and use that variable everywhere.

Furthermore, I think this would enable paring down the default set of services in the future, like you suggested in your forum post.

Of course, these new options should be documented in RST, but I would like to get your agreement and merge before putting work into the formal documentation.

2020-04-14 16:10 UTC, kdmccormick commented
Hi @alanoe - Ready for another round of review when you have the chance.
* For all of your review comments, I've either addressed them with `--fixup` commits or replied in-thread.
* I split the health check changes into `Rename healthchecks.sh to check.sh` and `Clean up check.sh and allow it to take multiple args`. 
* I went ahead and used `shellcheck` on all the scripts I changed this PR.

2020-04-17 11:34 UTC, alanoe commented on Makefile
> +%-restart: ## Kill a service's Django development server. The watcher process should restart it.
I like the approach of using a restart-django-devserver Make target (notice I suggested a "devserver" suffix to make it clear what you're restarting).

2020-04-17 11:42 UTC, alanoe commented on Makefile
> +endif
if SYNC_STRATEGY must be one of local-mounts, nfs or docker-sync and docker-compose.yml is used by all of them, I suggest you initialize DOCKER_COMPOSE FILES with "-f docker-compose.yml" and add other yml files depending on the value of SYNC_STRATEGY. This will reduce code duplication.

2020-04-17 11:48 UTC, alanoe commented on Makefile
> +	$(WINPTY) bash ./provision.sh $(DEFAULT_SERVICES)+e2e
Why are you adding e2e here? It seems to me that either it should be added to DEFAULT_SERVICES (best option) or you must update documentation explaining why it is added specifically in this target.

2020-04-17 11:55 UTC, alanoe commented on options.mk
> +# Variables are set here with ?= to allow for overriding them on the command line.
I think that adding support to a options.local.mk file with overrides should be done in a separate patch (before this one if it is a requirement).

2020-04-17 11:55 UTC, alanoe requested changes
minor: I suggest FS_SYNC_STRATEGY instead of SYNC_STRATEGY

2020-04-17 11:58 UTC, alanoe commented on Makefile
> +SUPPORTING_COMPOSE_FILES=-f docker-compose-host.yml -f docker-compose-themes.yml
This looks better than the previous implementation, +1

2020-04-17 11:59 UTC, alanoe commented
@kdmccormick Thanks for the changes! I agree with almost everything in the new PR, I have just added a few comments.

2020-04-20 14:18 UTC, kdmccormick commented on Makefile
> +%-restart: ## Kill a service's Django development server. The watcher process should restart it.
`make $service-restart-django-devserver` is a lot of typing, especially without target completion.

Would you be open to `$service-restart-devserver`? Your `make forums-restart` implementation in #512 could become `make forums-restart-devserver`.

2020-04-20 14:48 UTC, kdmccormick commented on Makefile
> +	$(WINPTY) bash ./provision.sh $(DEFAULT_SERVICES)+e2e
Yeah, `e2e` is a bit of a special snowflake, in that it's a provisioning target but it's not a service (essentially, it just gets some test data ready so that e2e tests can be run). I know this isn't the most elegant solution.

For this PR, I'll take your suggestion to add a comment of why it's being added here.

2020-04-20 14:59 UTC, kdmccormick commented on options.mk
> +# Variables are set here with ?= to allow for overriding them on the command line.
True. Reverted for now.

2020-04-20 15:16 UTC, kdmccormick commented on options.mk
> +# Variables are set here with ?= to allow for overriding them on the command line.
I remembering that I did this last week so that I could implement the old NFS targets as
```
dev.nfs.%:
	FS_SYNC_STRATEGY=nfs make dev.$*
```
I'll put the change in a separate commit.

2020-04-20 15:25 UTC, kdmccormick commented on Makefile
> +endif
Fixed this in `Simplify Makefile handling of docker-compose files`.

I added the `-f docker-compose.yml` after all the `if` branches so that the `ifndef DOCKER_COMPOSE_FILES` still works.

2020-04-20 15:32 UTC, alanoe commented
As soon as you do the small changes we have discussed, you already have my +1

2020-04-20 18:01 UTC, kdmccormick commented
Thanks for the thorough and helpful review @alanoe !

I pushed a final commit to make the log output cleaner (I didn't realize I needed `set -e` in TravisCI to exit early).

I'm going to ping the folks responsible for Discovery and eCommerce about these test failures in order to unblock our PRs.

2020-04-23 17:48 UTC, kdmccormick commented
I'm going to merge this with the eCommerce shard failing. We're seeing the exact same failure on `master`, and the failure occurs after the code paths that I feel need to be tested for this PR.

The eComm failure known of and is being looked into currently. It is likely an issue with https://github.com/edx/configuration associated with the ongoing configuration transition.

2020-04-23 17:49 UTC, merged

2020-10-05 14:42 UTC, feanil commented on .travis.yml
> -  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='analytics_pipeline'
There is a typo where this underscore was removed and we're seeing a breakage on master because a container with the name `analyticspipeline` doesn't exist.  https://travis-ci.org/github/edx/devstack/jobs/732970204  I'll make a pr to fix forward.

2020-10-05 14:46 UTC, kdmccormick commented on .travis.yml
> -  - DEVSTACK_WORKSPACE=/tmp SHALLOW_CLONE=1 DEVSTACK='analytics_pipeline'
@feanil I'm not sure if that's the issue. This was an intentional change, as `analyticspipeline` is the name of the service: https://github.com/edx/devstack/blob/master/docker-compose-analytics-pipeline.yml#L124

The CI build passed for analytics months after this merged.