Update MySQL databases initialization SQL scripts
openedx-unsupported/devstack pull request #508
Opened 2020-04-03 14:51 UTC by alanoe

Also create a shell script to do this update.

2020-04-03 14:52 UTC, edx-webhook commented
Thanks for the pull request, @alanoe! I've created [OSPR-4355](https://openedx.atlassian.net/browse/OSPR-4355) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

2020-04-03 17:21 UTC, kdmccormick requested changes
Thanks for the PR. I haven't tested this myself yet, but here are a few preliminary comments.

2020-04-03 17:21 UTC, kdmccormick commented on edxapp_csmh.sql
> +-- MySQL dump 10.13  Distrib 5.6.47, for Linux (x86_64)
@coryleeio I think you split the dump between `edxapp.sql` and `edxapp_csmh.sql`. Is updating these as simple as dumping both databases into their respective `.sql` files?

2020-04-03 17:21 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +set -u # exit when undefined variables are found
Today I learned about `set -u`. Nice.

2020-04-03 17:21 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +# Updates MySQL databases dumps with MySQL Docker container schema/data
Thanks for including the script you used!

Looking at the repo, it looks like there is already a `dump-db.sh`. If there are improvements here, could we roll them into that existing script instead?

2020-04-03 21:28 UTC, natabene commented
@alanoe Thank you for your contribution. Please let me know once all tests are green.

2020-04-07 18:20 UTC, alanoe commented on edxapp_csmh.sql
> +-- MySQL dump 10.13  Distrib 5.6.47, for Linux (x86_64)
Yes, it's done by the mysqldump command in the shell script in this PR.

2020-04-07 18:21 UTC, alanoe commented on update_dbs_init_sql_scripts.sh
> +set -u # exit when undefined variables are found
You're welcome   =)

2020-04-07 18:25 UTC, alanoe commented on update_dbs_init_sql_scripts.sh
> +# Updates MySQL databases dumps with MySQL Docker container schema/data
I haven't noticed that shell script before, thanks for mentioning it. I have replaced it with mine. I kept the new filename because IMHO it is more descriptive, but I can keep the old file name if you prefer.

IMHO the my new shell script is better because:
- it destroys any previous devstack and creates a new one with just ecommerce and lms before making the database dump
- it handles dbs usernames and passwords
- it copies the database dumps from the docker containers to the host, replacing the .sql scripts in this git repository

2020-04-07 18:27 UTC, alanoe commented
> Thanks for the PR. I haven't tested this myself yet, but here are a few preliminary comments.

You're welcome. I have made the changes requested in your comments and resubmitted the PR.

2020-04-08 13:05 UTC, kdmccormick commented on edxapp_csmh.sql
> +-- MySQL dump 10.13  Distrib 5.6.47, for Linux (x86_64)
Yup. I was curious why the database was split in the first place, and if that had any implications on how they should be dumped.

If you've manually tested this, though, then it should be fine.

2020-04-08 13:16 UTC, alanoe commented
@natabene All tests are green.

2020-04-08 13:24 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +# Updates MySQL databases dumps with MySQL Docker container schema/data
I like that your script re-provisions first. The name ` update_dbs_init_sql_scripts.sh ` doesn't communicate to me that my devstack will be destroyed in order to make a database dump, though. How about `reprovision-and-dump-db.sh`?

2020-04-08 13:37 UTC, kdmccormick requested changes
A few more requests, but I like where this is going.

2020-04-08 13:37 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

2020-04-08 13:37 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +MYSQL_CONTAINER=$(docker ps -aqf "name=mysql")
This seems a little unnecessarily generic, no? I'd prefer to either use the literal container name (`edx.devstack.mysql`), or even better, invoke the database dump using `docker-compose exec mysql` instead, which would be tolerant to the container being renamed.

2020-04-08 13:37 UTC, kdmccormick commented on README.rst
> +of manual intervention for existing installations (e.g. drop/move tables).
Could this be effectively automated in your script by just emptying the SQL files before provisioning?
```
for db_name in "${DBS[@]}"; do
    # Clear out SQL dump so that migrations are run from scratch when provisioning.
    echo > "$db_name".sql
done
```

2020-04-08 19:09 UTC, natabene commented
@alanoe Please sign the agreement, mentioned in other PR, so we can merge your code.

2020-04-09 00:32 UTC, alanoe commented on README.rst
> +of manual intervention for existing installations (e.g. drop/move tables).
I think so, although I don't clearly understand why someone would set the django_migrations table out of sync with the rest of the database and commit the dump of that inconsistent state to the git repository. I know it has happened since the last dump commit because I had to comment out the load-db.sh call when creating this patch.

2020-04-10 14:22 UTC, natabene commented
@alanoe Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

2020-04-13 16:08 UTC, kdmccormick commented on README.rst
> +of manual intervention for existing installations (e.g. drop/move tables).
I'm not sure either. I imagine it might have to do with times when want to do something that is difficult to do within Django Migrations (for example, moving a model from one app to another), so we work around it manually.

Up to you whether you want to add the existing-dump-deletion to your script (could be parameterized) or leave it as process in the README.

2020-04-17 10:57 UTC, alanoe commented on README.rst
> +of manual intervention for existing installations (e.g. drop/move tables).
As it is a hack, I prefer to leave it explicitly as a process in the README.

2020-04-17 10:59 UTC, alanoe commented
@kdmccormick I have updated the PR. Is there anything else which must be done here or can this PR be merged?

2020-04-20 13:45 UTC, kdmccormick commented
@alanoe Great! The only remaining comment I have is about [renaming the script](https://github.com/edx/devstack/pull/508/files#r405521896). Once that's addressed I'm good to merge this.

If tests keep failing and it's not due to the dump, I'll take make sure to take a look at that.

2020-04-20 15:25 UTC, alanoe commented on update_dbs_init_sql_scripts.sh
> +# Updates MySQL databases dumps with MySQL Docker container schema/data
As it does more than just dumping the dbs (it also replaces the current db initialization SQL scripts), I used reprovision-and-update-dbs-init-sql-scripts.sh. I was not sure if I should use dash ("-") or underscore ("_") as separator as there is no consistency in filenames here, but I changed to dash as most files are using it.

2020-04-20 15:52 UTC, kdmccormick commented on update_dbs_init_sql_scripts.sh
> +# Updates MySQL databases dumps with MySQL Docker container schema/data
Works for me! For potentially-destructive scripts that don't get run very often, airing on the side of verbosity seems like a good idea.

Yeah, the repo has both styles, but I prefer to side with the majority in this case. It'd be great to clean up the naming scheme some day.

2020-04-20 16:03 UTC, kdmccormick commented
I'm making sure I can provision a new devstack with these dumps. Once I'm able to do that, I'll go ahead and merge.

2020-04-20 17:40 UTC, kdmccormick requested changes
The updated dumps work great for provisioning. Thanks!

I found a couple issues while testing the script; see my comments.

Also, sorry for waffling further on this, but I'm realizing that `reprovision-and-update-dbs-init-sql-scripts.sh` is quite long. Your original name but with dashes (`update-dbs-init-sql-scripts.sh`) is better, especially given that `make destroy` prompts the user, so it's obvious that they'll need to reprovision. You could even remove the `dbs-` part to make it shorter (the SQL part implies that's it's going to effect the databases).

2020-04-20 17:40 UTC, kdmccormick commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    if [[ " ${DBS[@]} " =~ " ${EDXAPP_DBS} " ]]; then
I think conditional is bugged.

FWIW, I got it to work with
```bash
if [[ " ${DB_NAME} " =~ " ${EDXAPP_DBS[@]} " ]]; then
```

2020-04-20 17:40 UTC, kdmccormick commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    docker cp ${MYSQL_CONTAINER}:/${DB_CREATION_SQL_SCRIPT} .
`MYSQL_CONTAINER` is unbound.

Related, I realize now there's no `docker-compose cp` command, unfortunately. Most scripts in this repo assume the container name to be `edx.devstack.{service}` if you want to just reference `edx.devstack.mysql`, then that's fine.

One day it'd be cool to use `docker-compose` for everything in order to truly support multiple devstack workspaces.

2020-04-21 15:26 UTC, alanoe commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    docker cp ${MYSQL_CONTAINER}:/${DB_CREATION_SQL_SCRIPT} .
Fixed it. I'd prefer to use only docker instead of docker *and* docker-compose, but I've kept as it is.

As you surely know, docker-compose is just a convenience tool. Regardless of using it or not, we could support multiple devstacks by creating a devstack ID when a devstack is created, adding this ID to every Docker container name and requiring it in the devstack management commands we use (eg. make lms-restart, make lms-shell).

2020-04-21 16:32 UTC, kdmccormick commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    docker cp ${MYSQL_CONTAINER}:/${DB_CREATION_SQL_SCRIPT} .
I agree with your point on consistency -- using just `docker` instead of both `docker` and `docker-compose` makes sense. Up to your discretion here.

Yup, it's a tool, and like most tools, the more we conform to its idioms, the more functionality and documentation we get for free. We certainly *could* have a unique devstack ID in every reference to a container name, but if docker-compose does that for us, why reimplement it and be saddled with documenting it?

2020-04-23 19:08 UTC, kdmccormick commented on update-dbs-init-sql-scripts.sh
> +        MYSQL_DB_USER=${EDXAPP_MYSQL_DB_USER}
This condition evaluates to false for me when `DB_NAME` is `edxapp_csmh`

2020-04-24 19:57 UTC, alanoe commented on update-dbs-init-sql-scripts.sh
> +        MYSQL_DB_USER=${EDXAPP_MYSQL_DB_USER}
My bad, I had copy and pasted your suggestion without testing it. It is working now.

2020-04-24 20:03 UTC, alanoe commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    docker cp ${MYSQL_CONTAINER}:/${DB_CREATION_SQL_SCRIPT} .
KC> One day it'd be cool to use docker-compose for everything in order to truly support multiple devstack workspaces.

@kdmccormick Sorry, I thought you had meant in this comment that we required docker-compose to support multiple devstack workspaces. Instead, you meant that we should support multiple devstack workspaces and that we could use docker-compose for that. If it has such feature, sure, I agree.

2020-04-27 13:06 UTC, kdmccormick commented on reprovision-and-update-dbs-init-sql-scripts.sh
> +    docker cp ${MYSQL_CONTAINER}:/${DB_CREATION_SQL_SCRIPT} .
Gotcha, my bad for being unclear.

For reference, the [`COMPOSE_PROJECT_NAME`](https://docs.docker.com/compose/reference/envvars/#compose_project_name) is what I am thinking of.

2020-04-27 13:10 UTC, kdmccormick commented
@alanoe Once you push the fix the the conditional, I'll review and likely merge.

eCom and Discovery Tests should also be fixed now.

2020-04-29 14:04 UTC, kdmccormick commented
@alanoe I think the test suite has been fixed on master if you want to rebase.

2020-05-04 19:49 UTC, alanoe commented
> Also, sorry for waffling further on this, but I'm realizing that `reprovision-and-update-dbs-init-sql-scripts.sh` is quite long. Your original name but with dashes (`update-dbs-init-sql-scripts.sh`) is better, especially given that `make destroy` prompts the user, so it's obvious that they'll need to reprovision. You could even remove the `dbs-` part to make it shorter (the SQL part implies that's it's going to effect the databases).

OK. I have renamed the shell script back to update-dbs-init-sql-scripts.sh. I'd prefer to keep the "dbs" word.

2020-05-05 01:18 UTC, natabene commented
@kdmccormick I think this is ready for review again.

2020-05-05 14:07 UTC, kdmccormick approved these changes
Looks good. Thanks for the contribution, and thanks for sticking with me throughout the long review period.

2020-05-05 14:07 UTC, merged

2020-05-05 14:07 UTC, edx-webhook commented
@alanoe 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/508&entry.1484655318=https://github.com/alanoe&entry.752974735=2020-04-03+14:51&entry.1917517419=2020-05-05+14:07&entry.2133058324=Yes) so we can improve your experience in the future.