Allow project based backups and restores
openedx-unsupported/devstack pull request #554
Opened 2020-07-06 06:01 UTC by danialmalik

### Description
Now that the devstack allows having more than one devstacks per system, it would be better to have separate backup created for every project.

2020-07-06 06:01 UTC, edx-webhook commented
Thanks for the pull request, @danialmalik! I've created [OSPR-4798](https://openedx.atlassian.net/browse/OSPR-4798) to keep track of it in JIRA, where we prioritize reviews.  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.


<!-- jenkins ok to test -->

2020-07-06 21:03 UTC, natabene commented
@danialmalik Thank you for your contribution. Is this ready for edX review?

2020-07-07 04:30 UTC, danialmalik commented
@natabene this is ready to be reviewed from my side. I don't understand if the tests are failing due to my changes since my changes are totally unrelated to the tests being failed.

2020-07-07 13:25 UTC, jmbowman commented
I took a quick look; looks reasonable overall, but want to think a bit more about factors like how to restore backups made with the current code after these changes are made.  I've created a ticket for my team to finish reviewing in the next week or so: https://openedx.atlassian.net/browse/ARCHBOM-1335

The ecommerce tests have failed several times on master also recently, so I suspect that's unrelated.

2020-07-08 19:01 UTC, feanil requested changes
This will definitely break restoring from current backups since the location names will have changed.  Maybe we could temporarily add a migration target that will move from the old location to the new location?  Or we could pull the location out into a variable and calculate it's value to be the default value if `COMPOSE_PROJECT_NAME` is `devstack`?

I think I like the first option better since if the compose project that people made their backups from is not the default, the migration command should still work for them.

2020-07-14 18:48 UTC, feanil commented
@danialmalik closing this PR for now, please feel free to re-open with updates when you have them.

2020-07-14 18:48 UTC, closed without merging

2020-07-14 18:48 UTC, edx-webhook commented
@danialmalik Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/554&entry.1484655318=https://github.com/danialmalik&entry.752974735=2020-07-06+06:01&entry.1917517419=2020-07-14+18:48&entry.2133058324=No) so we can improve your experience in the future.