[BD-18] Fixes to run e2e tests on devstack
openedx-unsupported/devstack pull request #565
Opened 2020-07-24 12:20 UTC by ziafazal

Fixes to run e2e tests on devstack.

2020-07-24 12:21 UTC, ziafazal commented
@feanil @kdmccormick could you please review this PR?

2020-08-03 14:11 UTC, kdmccormick reviewed
Thanks for the PR. I'm excited to see e2e tests working in Devstack again!

I only have a couple of comments; I haven't tested this. @feanil will you be reviewing this, or did you want me to do a fuller review?

2020-08-03 14:11 UTC, kdmccormick commented on Makefile
> +
Does this have any effect? Ideally this should already be handled in [option.mk](https://github.com/edx/devstack/blob/master/options.mk#L35-L39).

2020-08-03 14:11 UTC, kdmccormick commented on Makefile
> +	docker run -t --network=$(COMPOSE_PROJECT_NAME)_default -v $(DEVSTACK_WORKSPACE)/edx-e2e-tests:/edx-e2e-tests --env-file $(DEVSTACK_WORKSPACE)/edx-e2e-tests/devstack_env edxops/e2e env TERM=$(TERM)
Regarding the `:-devstack` addition, I have the same comment as above about `options.mk`.

2020-08-04 13:29 UTC, feanil commented
@kdmccormick if you can do a further review, that would be great but I'm happy to take it if you're strapped for time.

2020-08-04 15:08 UTC, kdmccormick commented on Makefile
> +
I was able to get the tests working without this change. I believe that your other fixes are sufficient to get the tests running again.

2020-08-04 15:49 UTC, kdmccormick requested changes
Generally looks good!

I was able to run tests, but the ones I tried to run have failed. For example:
```
root@fa406f207ae7:/edx-e2e-tests# paver e2e_test common/test_html_component.py
```
gives:
```
bok_choy.page_object.PageLoadError: Message: Timed out waiting to load page 'CourseOutlinePageExtended(<browser>)' at URL 'http://studio.devstack.edx:18010/course/course-v1:edX+E2E-101+course'
```
That being said, at least the tests run now, which is better than before, so I'm happy to give my :+1: on this once my comments are addressed.

2020-08-04 15:49 UTC, kdmccormick commented on Makefile
>  e2e-tests: ## Run the end-to-end tests against the service containers.
```suggestion
e2e-tests: dev.up.lms+studio ## Run the end-to-end tests against the service containers.
```
How about making both this and `e2e-tests.with-shell` targets depend on `dev.up.lms+studio`? They break if those services haven't been brought up, right?

2020-08-05 07:21 UTC, ziafazal commented
@kdmccormick Thanks for reviewing. I have addressed feedback could you please take another look?

2020-08-05 13:16 UTC, kdmccormick approved these changes
Looks good, with the caveat that this just gets test to run for me, but not to pass.

2020-08-06 14:40 UTC, feanil commented
Ecom failure looks like it's happening on master as well.

2020-08-06 14:40 UTC, merged