Remove the non-release services from the default devstack services
openedx-unsupported/devstack pull request #566
Opened 2020-07-24 16:34 UTC by lgp171188

This is a backport of the changes made in https://github.com/edx/devstack/pull/559 and removes the non-release services from the list of default devstack services. 

**JIRA tickets**:  Will be created

**Discussions**: [Discussion on Open edX Slack](https://openedx.slack.com/archives/CK94QNCQ0/p1594902913283000)

**Dependencies**: None

**Merge deadline**: None

**Testing instructions**:
1. Checkout this PR branch and try to provision a fresh Juniper devstack by following the instructions in the `README` file.
2. Verify that the images for the `registrar`, `program-console` services and their dependencies are not pulled when running `make dev.pull`.
3. Verify that the devstack provisions successfully and works okay.

**Reviewers**:
- [ ] @kdmccormick?

2020-07-24 16:34 UTC, edx-webhook commented
Thanks for the pull request, @lgp171188! I've created [OSPR-4859](https://openedx.atlassian.net/browse/OSPR-4859) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.



<!-- comment:external_pr -->
<!-- jenkins ok to test -->

2020-07-24 18:28 UTC, nedbat commented
This PR is against master.  Did you mean to make it against open-release/juniper.master?

2020-07-24 18:40 UTC, lgp171188 commented
@nedbat, oops! I did intend to create it against `open-release/juniper.master`. Fixed now 🙂

2020-07-28 01:33 UTC, natabene commented
@lgp171188 Thank you for your contribution. Is this ready for our review?

2020-07-28 13:29 UTC, lgp171188 commented
@natabene, yes this is ready for review as it is a simple backport of the changes merged in https://github.com/edx/devstack/pull/559

2020-07-28 14:16 UTC, regisb approved these changes

2020-07-29 01:32 UTC, natabene commented
@kdmccormick Would you like to review and merge this as well, since you merged  #559

2020-08-03 13:55 UTC, kdmccormick requested changes
Sorry for the delay @lgp171188 @natabene ; I was out-of-office last week.

Other than this one change, I'm ready to approve and merge this.

2020-08-03 13:55 UTC, kdmccormick commented on README.rst
> +------------
Thanks for porting this section in; however, it's redundant with the existing **Service URLs** and **Microfrontend URLs** sections. Can you remove the old ones?

2020-08-03 19:13 UTC, lgp171188 commented on README.rst
> +------------
@kdmccormick, I have removed the old sections. Can you check and let me know if everything is okay now?

2020-08-07 13:26 UTC, kdmccormick approved these changes
Looks good! Thank you for rolling this fix @lgp171188 .

2020-08-07 13:26 UTC, merged

2020-08-07 13:26 UTC, edx-webhook commented
@lgp171188 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/566&entry.1484655318=https://github.com/lgp171188&entry.752974735=2020-07-24+16:34&entry.1917517419=2020-08-07+13:26&entry.2133058324=Yes) so we can improve your experience in the future.