Updated `README` to include necessary information when running multiple isolated devstacks for same host.
openedx-unsupported/devstack pull request #569
Opened 2020-07-27 20:59 UTC by ztraboo

This is the documentation needed for https://github.com/edx/devstack/pull/532

@kdmccormick, @jmbowman, @arbrandes, @regisb

2020-07-27 20:59 UTC, edx-webhook commented
Thanks for the pull request, @ztraboo! I've created [OSPR-4866](https://openedx.atlassian.net/browse/OSPR-4866) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.



<!-- comment:external_pr -->
<!-- jenkins ok to test -->

2020-07-27 21:02 UTC, ztraboo commented
Ready for edX review.

2020-07-28 14:41 UTC, regisb requested changes

2020-07-28 14:41 UTC, regisb commented on README.rst
> +-----------------------------------------------------
Nit: some rst parsers will fail if the number of `-` signs does not match the length of the title line.

2020-07-28 14:41 UTC, regisb commented on README.rst
> +Unfortunately, this **does not** currently support running Devstacks simultaneously, because we hard-code host port numbers all over the place, and as far as I know, two running containers cannot sha
because we hard-code host port numbers all over the place, and ~~as far as I know,~~ two running containers cannot share the same host port.

2020-07-28 14:41 UTC, regisb commented on README.rst
> +#. Bring down any running containers by issuing a `make dev.down`. This only needs to be done one time before provisioning the release as it will remove all service containers and networks.
Actually, `make dev.down` will also remove all volumes. It seems to me there are very few cases where we really want to do that. Shouldn't we run `make dev.stop` instead?

2020-07-28 14:41 UTC, regisb commented on README.rst
> +https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277
I think this link is unnecessary.

2020-07-28 14:41 UTC, regisb commented on README.rst
> +-  edx.devstack-juniper.master.frontend-app-publisher
Listing just one or two services should be enough.

2020-07-28 14:41 UTC, regisb commented on README.rst
> +Example of this can be found here https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277/6
This documentation should be self-contained as much as possible. I suggest we do not link to forum posts.

2020-07-28 14:41 UTC, regisb commented on README.rst
> +        Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
The formatting of this FAQ is a bit weird. I suggest the following:

```
Questions & Troubleshooting
~~~~~~~~~~~~~~~~~~~~~~~~~~~

This broke my existing Devstack!
================================

Try posting on ...

...
```

2020-07-28 14:41 UTC, regisb commented on README.rst
> +------------------------------------------------------------
I'm not sure if this section is very relevant. I would suggest a simple "Use direnv" sentence, with a link to the official docs. Maybe we could move this to the FAQ section?

2020-07-28 14:41 UTC, regisb commented on README.rst
> +Unfortunately, this **does not** currently support running Devstacks simultaneously, because we hard-code host port numbers all over the place, and as far as I know, two running containers cannot sha
I think most of this section should be moved further down such that users can find clear instructions right at the beginning. These are the instructions listed in "Switch between your Devstack projects by doing the following:"

2020-07-28 15:26 UTC, ztraboo commented on README.rst
> +#. Bring down any running containers by issuing a `make dev.down`. This only needs to be done one time before provisioning the release as it will remove all service containers and networks.
I agree with that @regisb. This is more words from @kdmccormick from here https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277. I've only run `make dev.down` whenever I need to remove all Docker containers. That's why I added that second sentence there about only doing this one time. I typically issue a `make stop.all` to stop all containers. Should we leave this or change it?

2020-07-28 15:26 UTC, ztraboo commented on README.rst
> +https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277
@regisb Yeah I debated it. I'll remove it and we can add it back in if needed.

2020-07-28 15:27 UTC, ztraboo commented on README.rst
> +-  edx.devstack-juniper.master.frontend-app-publisher
@regisb Ok I'll shorten that list.

2020-07-28 15:27 UTC, ztraboo commented on README.rst
> +Example of this can be found here https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277/6
@regisb Yep I'll remove that link to the forum post.

2020-07-28 15:28 UTC, ztraboo commented on README.rst
> +        Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
@regisb Ok I'll make that update.

2020-07-28 15:29 UTC, ztraboo commented on README.rst
> +------------------------------------------------------------
@regisb This is in the FAQ section of the README.rst file. Are you suggesting anywhere else?

2020-07-28 15:32 UTC, ztraboo commented on README.rst
> +Unfortunately, this **does not** currently support running Devstacks simultaneously, because we hard-code host port numbers all over the place, and as far as I know, two running containers cannot sha
@regisb I'll move this introduction text after the service names within that same section, so that, instructions are there first.

2020-07-28 15:36 UTC, regisb commented on README.rst
> +------------------------------------------------------------
Right, I didn't realise this section was in the FAQ. It's in the right place then, but I don't think it should include that much detailed information.

2020-07-28 15:38 UTC, regisb commented
FYI I'll be away from keyboard until Aug. 3rd, so I won't be able to revert my review until then.

2020-07-28 16:21 UTC, ztraboo commented
@regisb I made your recommended changes above. Please review https://github.com/CUCWD/devstack/blob/ztraboo/multiple-releases-one-machine-u1/README.rst#how-do-i-run-multiple-named-open-edx-releases-on-same-machine when you can. Thanks.

2020-07-28 16:38 UTC, regisb commented on README.rst
> +#. Setting the environment variables and enabling the `venv` using `direenv` makes switching named releases easier for devstack. Please follow directions `How do I enable environment variables for cu
I suggest we move this item further down or get rid of it entirely. It's redundant with the FAQ entry and it's not the first item that most people will be interested in when they actually want to run multiple devstacks.

2020-07-28 16:39 UTC, regisb commented on README.rst
> +#. The ``COMPOSE_PROJECT_NAME`` variable is used to define Docker namespaced volumes and network based on this value, so changing it will give you a
Shouldn't the right order be:

1. `make stop.all`
2. Define ``COMPOSE_PROJECT_NAME``
3. Perform steps in `How do I run the images for a named Open edX release?`_

?

2020-07-28 16:41 UTC, regisb commented on README.rst
> +#. Bring up the containers by issuing a ``make dev.up`` or ``make dev.up.all``.
I'm confused. Shouldn't we also follow the steps from the "How do I run the images for a named Open edX release?" section, including checking out the right branch from the devstack git repo?

2020-07-28 16:48 UTC, ztraboo commented on README.rst
> +#. Setting the environment variables and enabling the `venv` using `direenv` makes switching named releases easier for devstack. Please follow directions `How do I enable environment variables for cu
@regisb No problem I'll remove it.

2020-07-28 16:53 UTC, ztraboo commented on README.rst
> +#. The ``COMPOSE_PROJECT_NAME`` variable is used to define Docker namespaced volumes and network based on this value, so changing it will give you a
@regisb I'll reorder that based on what you mentioned ^.

2020-07-28 16:59 UTC, ztraboo commented on README.rst
> +#. Bring up the containers by issuing a ``make dev.up`` or ``make dev.up.all``.
@regisb Yes we want to run the steps from "How do I run the images for a named Open edX release?" section after we bring down any running containers. Then we need to actually provision the named release devstack if it isn't already provisioned. I'll add that step in now.

2020-07-28 17:05 UTC, ztraboo commented
@regisb I made those changes here https://github.com/CUCWD/devstack/tree/ztraboo/multiple-releases-one-machine-u1#how-do-i-run-multiple-named-open-edx-releases-on-same-machine. Please review when you have time.

2020-07-29 01:20 UTC, natabene commented
@nedbat This is ready, do you have some time to review it?

2020-08-02 13:17 UTC, regisb requested changes
A few additional minor changes are required. We're almost there!

2020-08-02 13:17 UTC, regisb commented on README.rst
> +#. Bring down any running containers by issuing a `make dev.stop`.
You should use two ticks in restructuredtext format:

    ``make dev.stop``

2020-08-02 13:17 UTC, regisb commented on README.rst
> +Many of you may use the ``OPENEDX_RELEASE`` environment variable to specify the version of named release services that are checked out during Devstack provisioning. If you set ``OPENEDX_RELEASE`` and
I wonder if this paragraph is still required? After all, there is already ample explanations concerning `OPENEDX_RELEASE` in the previous paragraph.

2020-08-02 13:17 UTC, regisb commented on README.rst
> +#. Bring up the containers by issuing a ``make dev.up`` or ``make dev.up.all``.
I believe you forgot to add the steps -- unless I'm mistaken?

2020-08-10 19:31 UTC, ztraboo commented on README.rst
> +#. Bring down any running containers by issuing a `make dev.stop`.
@regisb Added two ticks with https://github.com/edx/devstack/pull/569/commits/b4e7ff0f07696a27efd33c3edf8bcfdfdd1cdb44

2020-08-10 19:31 UTC, ztraboo commented on README.rst
> +Many of you may use the ``OPENEDX_RELEASE`` environment variable to specify the version of named release services that are checked out during Devstack provisioning. If you set ``OPENEDX_RELEASE`` and
@regisb Removed paragraph with https://github.com/edx/devstack/pull/569/commits/b4e7ff0f07696a27efd33c3edf8bcfdfdd1cdb44

2020-08-10 19:32 UTC, ztraboo commented
@regisb Sorry I was out last week. Please review changes with https://github.com/edx/devstack/pull/569/commits/b4e7ff0f07696a27efd33c3edf8bcfdfdd1cdb44 and let me know if you need me to revise anything.

2020-08-12 01:52 UTC, natabene commented
@regisb Thanks for reviewing this. CC @kdmccormick @jmbowman

2020-08-15 16:02 UTC, regisb commented on README.rst
> +#. Bring up the containers by issuing a ``make dev.up`` or ``make dev.up.all``.
This section assumes that `direnv` is a prerequisite of the Devstack and that all users should use direnv. This is not the case. I suggest that all direnv-related instructions be moved to the "How do I enable environment variables for current directory using 'direnv'?" section. The base instructions for running multiple releases at the same time should refer only to the "How do I run the images for a named Open edX release?" section.

Thus, I propose the following formulation:

```
#. Bring down the containers by issuing a ``make dev.stop`` for the running release.
#. Follow the instructions from the `How do I run multiple named Open edX releases on same machine?`_ section.
#. Edit the project name in ``options.local.mk`` or set the ``OPENEDX_RELEASE`` environment variable and let the ``COMPOSE_PROJECT_NAME`` be assigned automatically. Setting of the ``OPENEDX_RELEASE`` should have been handled within the ``.envrc`` file for named releases only and should not be defined for the ``master`` release.
#. Bring up the containers with ``make dev.up``.
```

Note that I removed the reference to ``make dev.up.all`` which seems to be deprecated.

2020-08-15 16:04 UTC, regisb commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
We should not encourage users to discuss issues on Slack. Instead, we should redirect them to the "troubleshooting" section in the readme.

2020-08-15 16:06 UTC, regisb commented on README.rst
> +Recommend separating the named releases into different directories since `direenv` unloads/loads different environment variables per directory.
I propose the following phrasing: "We recommend separating the named releases into different directories, for clarity purposes. You can use `direnv <https://direnv.net/>`__ to define different environment variables per directory::

2020-08-15 16:06 UTC, regisb requested changes
Please make sure all outstanding conversations can be resolved.

2020-08-15 19:10 UTC, ztraboo commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
This comment came from @kdmccormick from from this Discourse post https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277. Most of it did. That's why it's in the `Questions & troubleshooting` section. I can remove that and go to the troubleshooting section within the Readme instead like you mention.

2020-08-15 19:11 UTC, ztraboo commented on README.rst
> +Recommend separating the named releases into different directories since `direenv` unloads/loads different environment variables per directory.
@regisb Ok I'll make that change.

2020-08-15 20:18 UTC, ztraboo commented on README.rst
> +#. Bring up the containers by issuing a ``make dev.up`` or ``make dev.up.all``.
@regisb Made updates with https://github.com/edx/devstack/pull/569/commits/52c629ee3bef4aff86c245cf7e7792a36f5ef407. Please review.

2020-08-15 20:18 UTC, ztraboo commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
@regisb Made updates with https://github.com/edx/devstack/pull/569/commits/52c629ee3bef4aff86c245cf7e7792a36f5ef407. Please review.

2020-08-15 20:18 UTC, ztraboo commented on README.rst
> +Recommend separating the named releases into different directories since `direenv` unloads/loads different environment variables per directory.
@regisb Made updates with https://github.com/edx/devstack/pull/569/commits/52c629ee3bef4aff86c245cf7e7792a36f5ef407. Please review.

2020-08-15 20:19 UTC, ztraboo commented
@regisb Once we get this readme resolved I'll apply those changes to https://github.com/edx/devstack/pull/564 too. Thanks for the review.

2020-08-16 13:46 UTC, regisb commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
At the very least, I think we should remove the reference to Slack and add a link to the discourse forums:

     Try posting on the `Open edX forums <https://discuss.openedx.org>`__ to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.

2020-08-16 13:47 UTC, regisb commented on README.rst
> +Recommend separating the named releases into different directories since `direenv` unloads/loads different environment variables per directory.
Commit 52c629e did not affect this particular line.

2020-08-17 01:48 UTC, ztraboo commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
@regisb Apologize about this. Here is that update https://github.com/edx/devstack/pull/569/commits/89ff8de548e6b7a032aeb9644749908344b99e26.

2020-08-17 01:49 UTC, ztraboo commented on README.rst
> +Try posting on Discourse or Slack to see if you have the same issue as any others. If you think you have found a bug, file a CR ticket.
@regisb Apologize about this. Here is that update https://github.com/edx/devstack/pull/569/commits/89ff8de548e6b7a032aeb9644749908344b99e26.

2020-08-17 01:49 UTC, ztraboo commented on README.rst
> +Recommend separating the named releases into different directories since `direenv` unloads/loads different environment variables per directory.
@regisb Apologize about this. Here is that update https://github.com/edx/devstack/pull/569/commits/89ff8de548e6b7a032aeb9644749908344b99e26.

2020-08-17 08:41 UTC, regisb approved these changes

2020-08-17 08:42 UTC, merged

2020-08-17 08:42 UTC, edx-webhook commented
@ztraboo 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/569&entry.1484655318=https://github.com/ztraboo&entry.752974735=2020-07-27+20:59&entry.1917517419=2020-08-17+08:42&entry.2133058324=Yes) so we can improve your experience in the future.

2020-08-17 08:42 UTC, regisb commented
Thanks for your patience and cooperation @ztraboo!

2020-08-17 12:25 UTC, ztraboo commented
No problem @regisb. I appreciate a thorough review. Helps me code better. :)