Upgrade notes to elasticsearch7
openedx-unsupported/devstack pull request #621
Opened 2020-09-24 18:50 UTC by stvstnfrd

Note: This depends on https://github.com/edx/devstack/pull/612 .
This branch will be rebased and the PR re-pointed to `master` following #612 merging to `master`.

2020-09-25 17:50 UTC, stvstnfrd reviewed
@dianakhuang Who is best to confirm this works for notes?

I'm averse to merging it myself, as I haven't tested notes at all.

2020-09-25 17:50 UTC, stvstnfrd commented on docker-compose.yml
> +      ELASTICSEARCH_URL: "http://edx.devstack.elasticsearch7:9200"
This is one change that had _not_ already been in the previous WIP PR, but it _seems_ useful?

2020-09-25 17:52 UTC, kdmccormick commented on docker-compose.yml
> +      ELASTICSEARCH_URL: "http://edx.devstack.elasticsearch7:9200"
I believe you'll need this; otherwise, notes will keep pointing at the old ES container.

2020-09-25 18:10 UTC, dianakhuang commented on docker-compose.yml
> +      ELASTICSEARCH_URL: "http://edx.devstack.elasticsearch7:9200"
It doesn't hurt, but there is a new setting used for ES, which is why I didn't catch it before.

2020-09-25 19:23 UTC, dianakhuang commented
I'm having trouble with my docker volumes, but it seems like this works otherwise. I would say we should merge this and https://github.com/edx/edx-notes-api/pull/203 at the same time.

2020-09-25 20:05 UTC, dianakhuang approved these changes

2020-09-28 07:39 UTC, regisb requested changes

2020-09-28 07:39 UTC, regisb commented on docker-compose.yml
> +      ELASTICSEARCH_URL: "http://edx.devstack.elasticsearch7:9200"
Unless I'm mistaken, you will need to modify the hardcoded `ELASTICSEARCH_DSL['default']['hosts'] = 'edx.devstack.elasticsearch:9200'` in the devstack settings: https://github.com/edx/edx-notes-api/blob/6e339b1bbbb421efe52cb7737be4b61651a594a4/notesserver/settings/devstack.py#L16

2020-09-28 13:32 UTC, dianakhuang commented
@regisb yup, you are correct. I have a PR up for that: https://github.com/edx/edx-notes-api/pull/203

2020-09-28 20:44 UTC, davidjoy approved these changes

2020-09-29 07:23 UTC, regisb requested changes
Would you mind documenting the switch to ES7 in the README? It should include a "Temporary fixes" section which should also describe the progressive switch to MySQL 5.7. This is necessary to inform devstack users of this unexpected behaviour.

2020-09-29 14:33 UTC, dianakhuang commented
We're seeing `Failed to establish a new connection: [Errno 111] Connection refused` after merging the notes PR, so something is still broken in notes. I created https://github.com/edx/devstack/pull/626 to unblock provisioning until we can get ES7 working in devstack here.

2020-10-01 16:23 UTC, dianakhuang commented
Closing in favor of: https://github.com/edx/devstack/pull/630

2020-10-01 16:23 UTC, closed without merging