[Feat] Add the microfrontend account to the devstack on port 1997
openedx-unsupported/devstack pull request #822
Opened 2021-08-18 20:19 UTC by schenedx

Currently, the MFE frontend-app-account is not part of the optional microfrontends devstack can quickly help develop run. Add this devstack container for development

2021-08-18 20:26 UTC, kdmccormick requested changes
Nice! Thanks a lot for this PR. Three other places to add it:
* The "Service List" in README so folks know that it's there and what port it's on.
* The `EDX_SERVICES` list in options.mk, which will enable a bunch of Makefile rules to work on it.
* Either `repos` or `non_release_repos` in repo.sh (depending on whether or not the Account MFE is in Maple) so that it is cloned during provisioning.

Please also phrase your commit following the conventional commit syntax, eg `feat: Add the microfrontend account to the devstack on port 1997`

2021-08-19 01:10 UTC, schenedx commented
@kdmccormick I have updated the PR taking in all your feedback. Could you please review again to see if this is in the shape to merge?

2021-08-19 12:57 UTC, kdmccormick approved these changes
Just some alphabetization requests. Otherwise, looks great, and works on my machine 👍🏻 💯 

You may also want to rebase just to make sure this doesn't conflict with the Coursegraph stuff that just merged.

2021-08-19 12:57 UTC, kdmccormick commented on options.mk
> +credentials+discovery+ecommerce+edx_notes_api+forum+frontend-app-course-authoring+frontend-app-gradebook+frontend-app-learning+frontend-app-library-authoring+frontend-app-payment+frontend-app-program
```suggestion
credentials+discovery+ecommerce+edx_notes_api+forum+frontend-app-account+frontend-app-course-authoring+frontend-app-gradebook+frontend-app-learning+frontend-app-library-authoring+frontend-app-payment+frontend-app-program-console+frontend-app-publisher+lms+lms_watcher+registrar+registrar-worker+studio+studio_watcher+xqueue+xqueue_consumer
```
alphabetization

2021-08-19 12:57 UTC, kdmccormick commented on docker-compose.yml
> +  frontend-app-account:
Please place this at the top of the "edX Microfrontends" section for alphabetization

2021-08-19 12:57 UTC, kdmccormick commented on docker-compose-host.yml
> +  frontend_app_account_node_modules:
Please alphabetize this in the `volumes` list.

2021-08-19 12:57 UTC, kdmccormick commented on docker-compose-host.yml
> +      - ${DEVSTACK_WORKSPACE}/src:/edx/app/src:cached
Please place this right above frontend-app-course-authoring for alphabetization

2021-08-19 13:27 UTC, kdmccormick commented
@schenedx One other (non-blocking) thing you could do if you wanted to be REALLY awesome would be to add `localhost:1997` to this allowlist, which will make it the login page is willing to redirect you back to the Account MFE after logging in: https://github.com/edx/edx-platform/blob/d66d544ca255c7b174126e128e1999430b005640/lms/envs/devstack.py#L259-L275

If you don't do that, the MFE will still work fine. You'll just have to log in, and then navigate back to the localhost:1997 manually.

2021-08-19 13:28 UTC, schenedx commented
@kdmccormick Ha. I didn't know that existed. Will make a PR on edx-platform for it.

2021-08-19 13:33 UTC, schenedx commented
@kdmccormick according to your suggestion above, created https://github.com/edx/edx-platform/pull/28497

2021-08-19 14:21 UTC, merged